global:
  prefix: output/inhA

pipeline:
  - align

align:
  protocol: standard

  sequence_id: InhA
  sequence_file: data/sequences/InhA_MTUB.fasta

  database: path/to/uniref100.fasta

  iterations: 5

  seqid_filter: 0.8
  hhfilter: true

  minimum_sequence_coverage: 0.5
  minimum_column_coverage: 0.7

  use_bitscores: true
  domain_threshold: 0.3